{
 "title": "pgBackRest Exporter Dashboard",
 "description": "Dashboard works with pgbackrest_exporter",
 "tags": [
  "pgbackrest",
  "backups"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "label_values(host)" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "stanza",
    "label": "Stanza",
    "query": {
     "query": "label_values(pgbackrest_repo_status, stanza)"
    }
   },
   {
    "name": "repo_key",
    "label": "Repo key",
    "query": {
     "query": "label_values(pgbackrest_repo_status{stanza=~\"$stanza\"}, repo_key)"
    }
   },
   {
    "name": "backup_type",
    "label": "Backup type",
    "query": {
     "query": "label_values(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\"}, backup_type)"
    }
   },
   {
    "name": "block_incr",
    "label": "Block incr",
    "query": {
     "query": "label_values(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\"}, block_incr)"
    }
   },
   {
    "name": "backup_name",
    "label": "Backup name",
    "query": {
     "query": "label_values(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\",block_incr=~\"$block_incr\"}, backup_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stanzas CNT",
   "type": "stat",
   "description": "Count of selected stanzas.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (stanza)(pgbackrest_stanza_status{host=~\"$host\", stanza=~\"$stanza\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups CNT",
   "type": "stat",
   "description": "Count of all backups for selected stanzas and repos.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (stanza) (pgbackrest_backup_info{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full backups CNT",
   "type": "stat",
   "description": "Number of full backups for selected stanzas and repos.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (stanza) (pgbackrest_backup_info{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"full\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diff backups CNT",
   "type": "stat",
   "description": "Number of diff backups for selected stanzas and repos.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (stanza) (pgbackrest_backup_info{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incr backups CNT",
   "type": "stat",
   "description": "Number of incr backups for selected stanzas and repos.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (stanza) (pgbackrest_backup_info{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups with errors CNT",
   "type": "stat",
   "description": "Number of backups with errors for selected stanzas and repos.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbackrest_backup_error_status{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stanza status and last backups",
   "type": "table",
   "description": "Current stanza and active operations statuses for selected stanzas.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "pgbackrest_stanza_status{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "pgbackrest_backup_since_last_completion_seconds{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"full\"}"
    },
    {
     "expr": "pgbackrest_backup_since_last_completion_seconds{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"diff\"}"
    },
    {
     "expr": "pgbackrest_backup_since_last_completion_seconds{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"incr\"}"
    },
    {
     "expr": "pgbackrest_stanza_backup_lock_status{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "(pgbackrest_stanza_backup_complete_bytes{host=~\"$host\", stanza=~\"$stanza\"}/pgbackrest_stanza_backup_total_bytes{host=~\"$host\", stanza=~\"$stanza\"})*100"
    },
    {
     "expr": "pgbackrest_stanza_restore_lock_status{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "(pgbackrest_stanza_restore_complete_bytes{host=~\"$host\", stanza=~\"$stanza\"}/pgbackrest_stanza_restore_total_bytes{host=~\"$host\", stanza=~\"$stanza\"})*100"
    }
   ]
  },
  {
   "title": "Repository status",
   "type": "table",
   "description": "Current repository status for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "pgbackrest_repo_status{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\"}"
    }
   ]
  },
  {
   "title": "Backups CNT",
   "type": "timeseries",
   "description": "Number of backups for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (stanza) (pgbackrest_backup_info{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "WAL archive status",
   "type": "table",
   "description": "Current WAL archive status for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "pgbackrest_wal_archive_status{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\"}"
    }
   ]
  },
  {
   "title": "Average full uncompressed size of the database ",
   "type": "timeseries",
   "description": "Average full uncompressed size of the database for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_size_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
     "legendFormat": "{{ stanza }}"
    }
   ]
  },
  {
   "title": "Last backup error status and duration",
   "type": "table",
   "description": "Last backup error status and duration for selected stanzas.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "pgbackrest_backup_last_error_status{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "pgbackrest_backup_last_duration_seconds{host=~\"$host\", stanza=~\"$stanza\"}"
    }
   ]
  },
  {
   "title": "Total size occupied by backups in the repository",
   "type": "timeseries",
   "description": "Total size occupied by backups in the repository for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (stanza) (pgbackrest_backup_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
     "legendFormat": "{{ stanza }}"
    }
   ]
  },
  { "title": "Last backups info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Average last full backup duration",
   "type": "timeseries",
   "description": "Average last full backup duration for selected stanzas.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_duration_seconds{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"full\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average last diff backup duration",
   "type": "timeseries",
   "description": "Average last differential backup duration for selected stanzas.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_duration_seconds{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"diff\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average last incr backup duration",
   "type": "timeseries",
   "description": "Average last incremental backup duration for selected stanzas.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_duration_seconds{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"incr\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average size of last full backup in the repository",
   "type": "timeseries",
   "description": "Average size occupied by last full backup in the repository for selected stanzas.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", backup_type=~\"full\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average size of last diff backup in the repository",
   "type": "timeseries",
   "description": "Average size occupied by last differential backup in the repository for selected stanzas.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"diff\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average size of last incr backup in the repository",
   "type": "timeseries",
   "description": "Average size occupied by last  incremental backup in the repository for selected stanzas.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"incr\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Last backup size",
   "type": "table",
   "description": "For selected stanzas.\n\nBackup sizes:\n* **databaze size** - full uncompressed size of the database;\n* **database backup size** - the amount of data in the database to actually back up.\n\nThese will be the same for full backups.\n\nRepo sizes:\n* **repo backup set size** - includes all the files from this backup and any referenced backups in the repository that are required to restore the database from this backup;\n* **repo backup size** - includes only the files in this backup.\n\nThese will also be the same for full backups. Repository sizes reflect compressed file sizes if compression is enabled.\n\nSee https://pgbackrest.org/command.html#command-info\n\nFor block incremental backups **repo backup set size** is zero.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgbackrest_backup_last_size_bytes{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "pgbackrest_backup_last_delta_bytes{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "pgbackrest_backup_last_repo_size_bytes{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "pgbackrest_backup_last_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "pgbackrest_backup_last_repo_size_map_bytes{host=~\"$host\", stanza=~\"$stanza\"}"
    },
    {
     "expr": "pgbackrest_backup_last_repo_delta_map_bytes{host=~\"$host\", stanza=~\"$stanza\"}"
    }
   ]
  },
  {
   "title": "Number of annotations in the last backups",
   "type": "table",
   "description": "Number of annotations in the last backups for selected stanzas.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "pgbackrest_backup_last_annotations{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"full\"}"
    },
    {
     "expr": "pgbackrest_backup_last_annotations{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"diff\"}"
    },
    {
     "expr": "pgbackrest_backup_last_annotations{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"incr\"}"
    }
   ]
  },
  {
   "title": "Average number of annotations in the last backup",
   "type": "timeseries",
   "description": "Average number of annotations in the last backup for selected stanzas.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 63 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_annotations{host=~\"$host\", stanza=~\"$stanza\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Number of databases in the last backups",
   "type": "table",
   "description": "Number of databases in the last backups for selected stanzas.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "pgbackrest_backup_last_databases{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"full\"}"
    },
    {
     "expr": "pgbackrest_backup_last_databases{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"diff\"}"
    },
    {
     "expr": "pgbackrest_backup_last_databases{host=~\"$host\", stanza=~\"$stanza\", backup_type=\"incr\"}"
    }
   ]
  },
  {
   "title": "Average number of databases in the last backup",
   "type": "timeseries",
   "description": "Average number of databases in the last backup for selected stanzas.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 71 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_last_databases{host=~\"$host\", stanza=~\"$stanza\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  { "title": "General backups info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Average full backup duration",
   "type": "timeseries",
   "description": "Average full backup duration for selected stanzas and  repos.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_duration_seconds{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"full\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average diff backup duration",
   "type": "timeseries",
   "description": "Average differential backup duration for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_duration_seconds{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average incr backup duration",
   "type": "timeseries",
   "description": "Average incremental backup duration for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_duration_seconds{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average size of full backup in the repository",
   "type": "timeseries",
   "description": "Average size occupied by full backup in the repository for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"full\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average size of diff backup in the repository",
   "type": "timeseries",
   "description": "Average size occupied by differential backup in the repository for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average size of incr backup in the repository",
   "type": "timeseries",
   "description": "Average size occupied by incremental backup in the repository for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average number of annotations in the full backup",
   "type": "timeseries",
   "description": "Average number of annotations in the full backup for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_annotations{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"full\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average number of annotations in the diff backup",
   "type": "timeseries",
   "description": "Average number of annotations in the diff backup for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_annotations{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average number of annotations in the incr backup",
   "type": "timeseries",
   "description": "Average number of annotations in the incr backup for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_annotations{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average number of databases in the full backup",
   "type": "timeseries",
   "description": "Average number of databases in the full backup for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_databases{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"full\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average number of databases in the diff backup",
   "type": "timeseries",
   "description": "Average number of databases in the diff backup for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_databases{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Average number of databases in the incr backup",
   "type": "timeseries",
   "description": "Average number of databases in the incr backup for selected stanzas and repos.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "targets": [
    {
     "expr": "avg by (stanza) (pgbackrest_backup_databases{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"})",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  { "title": "Detailed backups info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Backup error status",
   "type": "table",
   "description": "Backup error status for selected stanzas, repos, backup types, block incremental statuses and backup names.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "pgbackrest_backup_error_status{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "table",
   "description": "Backup duration for selected stanzas, repos, backup types, block incremental statuses and backup names.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "pgbackrest_backup_duration_seconds{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
    }
   ]
  },
  {
   "title": "Backup size",
   "type": "table",
   "description": "For selected stanzas, repos, backup types, block incremental statuses and backup names.\n\nBackup sizes:\n* **databaze size** - full uncompressed size of the database;\n* **database backup size** - the amount of data in the database to actually back up.\n\nThese will be the same for full backups.\n\nRepo sizes:\n* **repo backup set size** - includes all the files from this backup and any referenced backups in the repository that are required to restore the database from this backup;\n* **repo backup size** - includes only the files in this backup.\n\nThese will also be the same for full backups. Repository sizes reflect compressed file sizes if compression is enabled.\n\nSee https://pgbackrest.org/command.html#command-info\n\nFor block incremental backups **repo backup set size** is zero.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgbackrest_backup_size_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "pgbackrest_backup_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "pgbackrest_backup_repo_size_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "pgbackrest_backup_repo_delta_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "pgbackrest_backup_repo_size_map_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "pgbackrest_backup_repo_delta_map_bytes{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    }
   ]
  },
  {
   "title": "Backup detail info",
   "type": "table",
   "description": "Backup detail info for selected stanzas, repos, backup types, block incremental statuses and backup names.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "pgbackrest_backup_info{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    }
   ]
  },
  {
   "title": "Number of annotations in the backup",
   "type": "table",
   "description": "Number of annotations in the backup for selected stanzas, repos, backup types, block incremental statuses and backup names.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "pgbackrest_backup_annotations{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    }
   ]
  },
  {
   "title": "Number of databases in the backup",
   "type": "table",
   "description": "Number of databases in the backup for selected stanzas, repos, backup types, block incremental statuses and backup names.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 156 },
   "targets": [
    {
     "expr": "pgbackrest_backup_databases{host=~\"$host\", stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", block_incr=~\"$block_incr\", backup_name=~\"$backup_name\"}"
    }
   ]
  },
  { "title": "pgBackRest Exporter info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "Exporter status and build info",
   "type": "table",
   "description": "Information about exporter build parameters and status of getting data from  pgBackRest.\n\nWhen the information is collected for all available stanzas, the **stanza for metrics** is **all-stanzas**.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "pgbackrest_exporter_build_info{host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pgbackrest_exporter_status{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pgBackRest info",
   "type": "table",
   "description": "Information about installed pgBackrest on instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "pgbackrest_version_info{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}