---
# NOTE: use 'sops updatekeys --yes secrets.yaml' to add/remove recipients.
keys:
  - &user_vijay age1zgyq9gpx5wnwt3dl5gzy2zch97khe0f78dfeed7v4gzwurvkkays0pn4nd
  - &host_kakashi age1xt2sxr7cegrrut84q49tczqgsmhn0kkahk8sclyt02jqwwywpq8sq49tq8
  - &host_usopp age1sx50q6uprsd0cnxtcd8cqchfywk89jqg2fgkw7d3krv6c3vyj37qy7v87e
  - &host_zoro age1mp9z7cghnua972jzjvrjl7v5nafplwytwceaf35ma8ae9j23kues7xqzr4
  - &host_nami age1sngmeyjqugqxp58eveqsyx5afay58affgexhgamvf2jx8g03h48q3qulhx
  - &host_chopper age1eszjmjjsmn9npdlv23dvv9y9qy769qnut7xp663yflu9qmsgc9lsvnuvrm
  - &host_franky age1a3lp6tzzzztevneuc52yll8zdyxe0qvpj74qcx30hplt7xug69zsz8q2v8
  - &host_robin age1hkqygt3aknuc34sh2u2j7xdzr68009r7zzunrk9xlhvn8mgygaxsqhvazg
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user_vijay
          - *host_kakashi
          - *host_usopp
          - *host_zoro
          - *host_nami
          - *host_chopper
          - *host_franky
          - *host_robin
